routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|c
*/

// for generate dummy record log
// Route::get('query', 'SeederController@dummyScan');

Route::get('/', function () {
    return redirect('dashboard');
});

Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    // USER MANAGEMENT
    Route::prefix('user-management')->group(function () {
        // employee
        Route::get('/employee/ajaxDatatable', 'UserManagement\EmployeeController@ajaxDatatable')->name('employee.ajaxDatatable');
        Route::resource('employee', 'UserManagement\EmployeeController', ['names' => 'employee']);

        // user-account
        Route::get('/user-account/ajaxDatatable', 'UserManagement\UserAccountController@ajaxDatatable')->name('user-account.ajaxDatatable');
        Route::resource('user-account', 'UserManagement\UserAccountController', ['names' => 'user-account']);
    });

    // MASTER
    Route::prefix('master')->group(function () {
        // fever
        Route::resource('fever', 'Master\FeverController', ['names' => 'fever']);
        // absence
        Route::get('/absence/ajaxDatatable', 'Master\AbsenceController@ajaxDatatable')->name('absence.ajaxDatatable');
        Route::resource('absence', 'Master\AbsenceController', ['names' => 'absence']);
    });

    // MONITORING
    Route::prefix('monitoring')->group(function () {
        Route::get('/live-scan', 'Monitoring\LiveScanController@index')->name('live-scan');
        Route::get('/live-scan-monitor', 'Monitoring\LiveScanController@monitor')->name('live-scan-monitor');
    });

    // REPORT
    Route::prefix('report')->group(function () {
        // scanning report
        Route::get('/scanning-report/ajaxDatatable', 'Report\ScanningReportController@ajaxDatatable')->name('scanning-report.ajaxDatatable');
        Route::resource('scanning-report', 'Report\ScanningReportController', ['names' => 'scanning-report']);

        // absence report
        Route::get('/absence-report/ajaxDatatable', 'Report\AbsenceReportController@ajaxDatatable')->name('absence-report.ajaxDatatable');
        Route::resource('absence-report', 'Report\AbsenceReportController', ['names' => 'absence-report']);
    });
});

Auth::routes();

app/Http/Controllers/Master/AbsenceController.php
<?php

namespace App\Http\Controllers\Master;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\{ AbsenceRepository };
use App\Http\Requests\AbsenceRequest;
use Yajra\Datatables\Datatables;

class AbsenceController extends Controller
{
    protected $absence;

    public function __construct(AbsenceRepository $absence)
    {
        $this->absence = $absence;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('master.absence_index');
    }

    public function create()
    {
        return view('master.absence_create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AbsenceRequest $request)
    {
        $store = $this->absence->store($request->all());

        return redirect()->route('absence.index')->with(\Helper::alertStatus('store', $store));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int
     * @return \Illuminate\Http\Response
     */
    public function update(AbsenceRequest $request, $AbsenceID)
    {
        $update = $this->absence->update($request->all(), $AbsenceID);

        return redirect()->route('absence.index')->with(\Helper::alertStatus('update', $update));
    }

    /**
     * Display the specified resource.
     *
     * @param  int
     * @return \Illuminate\Http\Response
     */
    public function show($AbsenceID)
    {
        $absence = $this->absence->show($AbsenceID);

        return view('master.absence_show', compact('absence'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int
     * @return \Illuminate\Http\Response
     */
    public function edit($AbsenceID)
    {
        $absence  = $this->absence->show($AbsenceID);

        return view('master.absence_edit', compact('absence'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->absence->delete($id);
    }

    /**
    * Showing list bank by datatable
    * @param $request ajax
    * @return json
    */
    public function ajaxDatatable(Request $request)
    {
        $absence = $this->absence->all();

        return Datatables::of($absence)
                ->addColumn('action', function ($absence) {
                    return '
                                <a class="datatable-buttons" href="' .route("absence.edit", $absence->ID). '" title="Edit user">
                                    <i class="mdi mdi-pencil-box-outline icon-md text-primary"></i>
                                </a>&nbsp;
                                
                            ';
                })
                ->rawColumns(['action'])
                ->make(true);
    }
}

app/Http/Controllers/Master/FeverController.php
<?php

namespace App\Http\Controllers\Master;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\{ FeverRepository };
use App\Http\Requests\FeverRequest;

class FeverController extends Controller
{
    protected $fever;

    public function __construct(FeverRepository $fever)
    {
        $this->fever = $fever;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $fever = $this->fever->show(1);

        return view('master.fever_index', compact('fever'));
    }

    public function update(FeverRequest $request, $feverID)
    {
        $request['temperature'] = str_replace('.', ',', $request->temperature);
        $update = $this->fever->update($request->all(), $feverID);

        return redirect()->route('fever.index')->with(\Helper::alertStatus('update', $update));
    }
}

resources/views/master/absence_create.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="./assets/vendors/pickadate/themes/default.css">
<link rel="stylesheet" href="./assets/vendors/pickadate/themes/default.time.css">
<script src="./assets/vendors/pickadate/picker.js"></script>
<script src="./assets/vendors/pickadate/picker.time.js"></script>
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Absence</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-description">Create Absence</p>
                    <form class="forms-sample" id="form-create-absence" action="{{ route('absence.store') }}" method="post">
                        @csrf
                        @include('partials.form-input', [
                          'title'       => __('Start Time'),
                          'type'        => 'text',
                          'name'        => 'StartTime',
                          'class'       => 'timepicker',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('End Time'),
                          'type'        => 'text',
                          'name'        => 'EndTime',
                          'class'       => 'timepicker',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Status'),
                          'type'        => 'text',
                          'name'        => 'Status',
                          'required'    => true
                        ])
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a href="{{ route('absence.index') }}" class="btn btn-dark">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\AbsenceRequest', '#form-create-absence') !!}
<script>
    $(document).ready(function() {
        // set navigation link active
        $('.nav-link[href="#master"]').parent().addClass('active');
        $('.link-absence').addClass('active')
        $('.link-absence').parent().parent().parent().addClass('show')

        $('.timepicker').pickatime({
            format: 'H:i'
        })
    });
</script>
@endsection

resources/views/master/absence_edit.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="./assets/vendors/pickadate/themes/default.css">
<link rel="stylesheet" href="./assets/vendors/pickadate/themes/default.time.css">
<script src="./assets/vendors/pickadate/picker.js"></script>
<script src="./assets/vendors/pickadate/picker.time.js"></script>
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Absence</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-description">Edit Absence</p>
                    <form class="forms-sample" id="form-edit-absence" action="{{ route('absence.update', $absence->ID) }}" method="post">
                        @csrf
                        {{ method_field('PATCH') }}
                        @include('partials.form-input', [
                          'title'       => __('Start Time'),
                          'type'        => 'text',
                          'name'        => 'StartTime',
                          'class'       => 'timepicker',
                          'required'    => true,
                          'value'       => $absence->StartTime
                        ])
                        @include('partials.form-input', [
                          'title'       => __('End Time'),
                          'type'        => 'text',
                          'name'        => 'EndTime',
                          'class'       => 'timepicker',
                          'required'    => true,
                          'value'       => $absence->EndTime
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Status'),
                          'type'        => 'text',
                          'name'        => 'Status',
                          'required'    => true,
                          'value'       => $absence->Status
                        ])
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a href="{{ route('absence.index') }}" class="btn btn-dark">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\AbsenceRequest', '#form-edit-absence') !!}
<script>
    $(document).ready(function() {
        // set navigation link active
        $('.nav-link[href="#master"]').parent().addClass('active');
        $('.link-absence').addClass('active')
        $('.link-absence').parent().parent().parent().addClass('show')

        $('.timepicker').pickatime({
            format: 'H:i'
        })
    });
</script>
@endsection

resources/views/master/absence_index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Absence</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    @include('partials.alert')
                    {{-- <div>
                        <a class="btn btn-primary btn-icon-text" href="{{ route('absence.create') }}">
                            <i class="mdi mdi-note-plus btn-icon-prepend"></i> 
                            Add Absence 
                        </a>
                    </div> --}}
                    <br />
                      <table class="table table-bordered" id="table">
                        <thead>
                          <tr>
                            <th> No </th>
                            <th> Start Time </th>
                            <th> End Time </th>
                            <th> Status </th>
                            <th> Action </th>
                          </tr>
                        </thead>
                      </table>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        // datatable
        var table = $('#table').DataTable({
         processing: true,
         serverSide: true,
         searching: false,
         ordering: false,
         ajax: '{{ route('absence.ajaxDatatable') }}',
         columns: [
             {
                "data": "id",
                "width": "5%",
                render: function (data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                } 
             },
             {data: 'StartTime', name: 'Absence.StartTime', width: "10%"},
             {data: 'EndTime', name: 'Absence.EndTime', width: "10%"},
             {data: 'Status', name: 'Absence.Status', width: "15%"},
             {data: 'action', className: 'text-center', width: "10%"}
         ],
         "drawCallback": function(settings) {
         
          },            
             pageLength: 10,
         });
    });
</script>
@include('partials.datatable-delete', ['text' => 'Absence', 'table' => '#table'])
@endsection

resources/views/master/absence_show.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">User Account</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-description">Detail User Account</p>
                    <form class="forms-sample">
                        @include('partials.form-select', [
                          'title'    => __('Employee'),
                          'name'     => 'UserID',
                          'data'     => $employees,
                          'required' => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Email'),
                          'type'        => 'email',
                          'name'        => 'email',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Password'),
                          'type'        => 'password',
                          'name'        => 'password',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Confirm Password'),
                          'type'        => 'password',
                          'name'        => 'password_confirmation',
                          'required'    => true
                        ])
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a href="{{ route('user-account.index') }}" class="btn btn-dark">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\UserAccountRequest', '#form-create-user-account') !!}
<script>
    $(document).ready(function() {
        // set navigation link active
        $('.nav-link[href="#user-management"]').parent().addClass('active');
        $('.link-user-account').addClass('active')
        $('.link-user-account').parent().parent().parent().addClass('show')

    });
</script>
@endsection

resources/views/master/fever_index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Fever</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="alert alert-success mt-4 d-flex align-items-center" role="alert" style="margin:20px 30px !important">
                    <i class="ti-info-alt"></i>
                    <p>
                        Set the temperature limit for fever. for example if we set the temperature 37.5&#8451; then below that temperature condition will be "normal" but more than 37.5&#8451; condition will be "fever"
                    </p>
                </div>
                @include('partials.alert')
                <div class="card-body">
                    <form class="forms-sample" id="form-edit-fever" action="{{ route('fever.update', $fever->FeverID) }}" method="post">
                        @csrf
                        {{ method_field('PATCH') }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Temperature</label>
                            <div class="input-group col-sm-6">
                                <input type="number" class="form-control" name="temperature" value="{{ $fever->temperature }}" />
                                <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon2">
                                        &#8451;
                                    </span>
                                </div>
                            </div>
                        </div>
                        <br />
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\FeverRequest', '#form-edit-fever') !!}
@endsection

resources/views/master/oldworking_time_index.blade.php
@extends('layouts.app')
@section('content')
<link rel="stylesheet" href="./assets/vendors/pickadate/themes/default.css">
<link rel="stylesheet" href="./assets/vendors/pickadate/themes/default.time.css">
<script src="./assets/vendors/pickadate/picker.js"></script>
<script src="./assets/vendors/pickadate/picker.time.js"></script>
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Working Time</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="alert alert-success mt-4 d-flex align-items-center" role="alert" style="margin:20px 30px !important">
                    <i class="ti-info-alt"></i>
                    <p>
                        Set the start and end of working time in order to get employee status of presence. below start time then status will be "on time" but if more than start time start time will be "late"
                    </p>
                </div>
                @include('partials.alert')
                <div class="card-body">
                    <form class="forms-sample" id="form-edit-working-time" action="{{ route('working-time.update', $workingTime->WorkingTimeID) }}" method="post">
                        @csrf
                        {{ method_field('PATCH') }}
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">Start Time</label>
                            <div class="input-group col-sm-6">
                                <input type="text" class="form-control timepicker" name="StartTime" value="{{ $workingTime->StartTime }}" />
                                <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon2">
                                        <i class="mdi mdi-timetable"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-sm-2 col-form-label">End Time</label>
                            <div class="input-group col-sm-6">
                                <input type="text" class="form-control timepicker" name="EndTime" value="{{ $workingTime->EndTime }}" />
                                <div class="input-group-append">
                                    <span class="input-group-text" id="basic-addon2">
                                        <i class="mdi mdi-timetable"></i>
                                    </span>
                                </div>
                            </div>
                        </div>
                        <br />
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{!! JsValidator::formRequest('App\Http\Requests\WorkingTimeRequest', '#form-edit-working-time') !!}
<script>
    $('.timepicker').pickatime({
        format: 'H:i'
    })
</script>
@endsection