routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|c
*/

// for generate dummy record log
// Route::get('query', 'SeederController@dummyScan');

Route::get('/', function () {
    return redirect('dashboard');
});

Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    // USER MANAGEMENT
    Route::prefix('user-management')->group(function () {
        // employee
        Route::get('/employee/ajaxDatatable', 'UserManagement\EmployeeController@ajaxDatatable')->name('employee.ajaxDatatable');
        Route::resource('employee', 'UserManagement\EmployeeController', ['names' => 'employee']);

        // user-account
        Route::get('/user-account/ajaxDatatable', 'UserManagement\UserAccountController@ajaxDatatable')->name('user-account.ajaxDatatable');
        Route::resource('user-account', 'UserManagement\UserAccountController', ['names' => 'user-account']);
    });

    // MASTER
    Route::prefix('master')->group(function () {
        // fever
        Route::resource('fever', 'Master\FeverController', ['names' => 'fever']);
        // absence
        Route::get('/absence/ajaxDatatable', 'Master\AbsenceController@ajaxDatatable')->name('absence.ajaxDatatable');
        Route::resource('absence', 'Master\AbsenceController', ['names' => 'absence']);
    });

    // MONITORING
    Route::prefix('monitoring')->group(function () {
        Route::get('/live-scan', 'Monitoring\LiveScanController@index')->name('live-scan');
        Route::get('/live-scan-monitor', 'Monitoring\LiveScanController@monitor')->name('live-scan-monitor');
    });

    // REPORT
    Route::prefix('report')->group(function () {
        // scanning report
        Route::get('/scanning-report/ajaxDatatable', 'Report\ScanningReportController@ajaxDatatable')->name('scanning-report.ajaxDatatable');
        Route::resource('scanning-report', 'Report\ScanningReportController', ['names' => 'scanning-report']);

        // absence report
        Route::get('/absence-report/ajaxDatatable', 'Report\AbsenceReportController@ajaxDatatable')->name('absence-report.ajaxDatatable');
        Route::resource('absence-report', 'Report\AbsenceReportController', ['names' => 'absence-report']);
    });
});

Auth::routes();

app/Http/Controllers/UserManagement/EmployeeController.php
<?php

namespace App\Http\Controllers\UserManagement;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\RecordLogRepository;
use App\Services\ConditionService;
use App\Services\ScanService;
use Yajra\Datatables\Datatables;

class EmployeeController extends Controller
{
    public function __construct(ScanService $scan, ConditionService $condition)
    {
        $this->scan = $scan;
        $this->condition = $condition;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user_management.employee_index');
    }

    /**
    * Showing list bank by datatable
    * @param $request ajax
    * @return json
    */
    public function ajaxDatatable(Request $request)
    {
        $condition = $this->condition;
        $scan      = $this->scan;
        $employee = \DB::select(
            \DB::raw(
                'SELECT UserInfo.UserID, UserInfo.UserName, UserGroup.GroupName AS Department
                 FROM UserInfo 
                 INNER JOIN UserGroup ON UserInfo.GroupID = UserGroup.ID
                 ORDER BY UserName;
                '
            )
        );

        return Datatables::of($employee)
                ->addColumn('LastScan', function ($employee) use ($scan) {
                    return $scan->lastTimeScan($employee->UserID);
                })
                ->addColumn('Condition', function ($employee) use ($condition) {
                    $conditionText = '-';
                    $employeeFever = $condition->employeeFever($employee->UserID);

                    if ($employeeFever === true) {
                        return '<label class="badge badge-danger">Fever</label>';
                    }
                    if ($employeeFever === false) {
                        return '<label class="badge badge-success">Normal</label>';
                    }

                    return '<label class="badge badge-info">No data</label>';
                })
                ->rawColumns(['Condition']) // to html
                ->make(true);
    }
}

app/Http/Controllers/UserManagement/UserAccountController.php
<?php

namespace App\Http\Controllers\UserManagement;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\EmployeeRepository;
use App\Repositories\UserAccountRepository;
use App\Http\Requests\UserAccountRequest;
use Yajra\Datatables\Datatables;

class UserAccountController extends Controller
{
    public function __construct(UserAccountRepository $userAccount, EmployeeRepository $employee)
    {
        $this->employee    = $employee;
        $this->userAccount = $userAccount;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user_management.user_account_index');
    }

    public function create()
    {
        $userAccountIds = $this->userAccount->getModel()->pluck('UserId');
        $employees = $this->employee->getModel()->whereNotIn('UserID', $userAccountIds)->pluck('UserName', 'UserID');

        return view('user_management.user_account_create', compact('employees'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserAccountRequest $request)
    {
        $request['password']   = bcrypt($request['password']);
        $request['username']   = $this->employee->where(['UserID' => $request->UserID])->value('UserName');
        $request['created_at'] = date('Y-m-d H:i:s');
        $request['updated_at'] = date('Y-m-d H:i:s');

        $store = $this->userAccount->store($request->except(['password_confirmation']));

        return redirect()->route('user-account.index')->with(\Helper::alertStatus('store', $store));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int
     * @return \Illuminate\Http\Response
     */
    public function update(UserAccountRequest $request, $userId)
    {
        if ($request['password'] == '') {
            unset($request['password']);
        } else {
            $request['password'] = bcrypt($request['password']);
        }

        $update = $this->userAccount->update($request->except(['password_confirmation']), $userId);

        return redirect()->route('user-account.index')->with(\Helper::alertStatus('update', $update));
    }

    /**
     * Display the specified resource.
     *
     * @param  int
     * @return \Illuminate\Http\Response
     */
    public function show($userId)
    {
        $user = $this->userAccount->show($userId);

        return view('user_management.user_account_show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int
     * @return \Illuminate\Http\Response
     */
    public function edit($userId)
    {
        $user  = $this->userAccount->show($userId);

        return view('user_management.user_account_edit', compact('user'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->userAccount->delete($id);
    }

    /**
    * Showing list bank by datatable
    * @param $request ajax
    * @return json
    */
    public function ajaxDatatable(Request $request)
    {
        $userAccount = $this->userAccount->all();

        return Datatables::of($userAccount)
                ->addColumn('created_at', function ($userAccount) {
                    return \Helper::tglIndo($userAccount->created_at);
                })
                ->addColumn('updated_at', function ($userAccount) {
                    return \Helper::tglIndo($userAccount->updated_at);
                })
                ->addColumn('action', function ($userAccount) {
                    return '
                                <a class="datatable-buttons" href="' .route("user-account.edit", $userAccount->ID). '" title="Edit user">
                                    <i class="mdi mdi-pencil-box-outline icon-md text-primary"></i>
                                </a>&nbsp;
                                <a class="datatable-buttons btn-delete-datatable" href="' .route("user-account.destroy", $userAccount->ID). '" title="Delete user">
                                    <i class="mdi mdi-delete icon-md text-primary"></i>
                                </a>
                            ';
                })
                ->rawColumns(['action'])
                ->make(true);
    }
}

resources/views/user_management/employee_index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">Employee</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                      <table class="table table-bordered" id="table">
                        <thead>
                          <tr>
                            <th> No </th>
                            <th> Username </th>
                            <th> Department </th>
                            <th> Last Scan </th>
                            <th> Condition </th>
                          </tr>
                        </thead>
                      </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        // datatable
        var table = $('#table').DataTable({
         processing: true,
         serverSide: true,
         searching: false,
         ordering: false,
         ajax: '{{ route('employee.ajaxDatatable') }}',
         columns: [
             {
                "data": "id",
                render: function (data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                } 
             },
             {data: 'UserName', name: 'UserInfo.UserName'},
             {data: 'Department', name: 'UserGroup.GroupName'},
             {data: 'LastScan'},
             {data: 'Condition'},
         ],
         "drawCallback": function(settings) {
         
          },            
             pageLength: 10,
         });
    });
</script>
@endsection

resources/views/user_management/user_account_create.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">User Account</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-description">Create User Account</p>
                    <form class="forms-sample" id="form-create-user-account" action="{{ route('user-account.store') }}" method="post">
                        @csrf
                        @include('partials.form-select', [
                          'title'    => __('Employee'),
                          'name'     => 'UserID',
                          'data'     => $employees,
                          'required' => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Email'),
                          'type'        => 'email',
                          'name'        => 'email',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Password'),
                          'type'        => 'password',
                          'name'        => 'password',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Confirm Password'),
                          'type'        => 'password',
                          'name'        => 'password_confirmation',
                          'required'    => true
                        ])
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a href="{{ route('user-account.index') }}" class="btn btn-dark">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\UserAccountRequest', '#form-create-user-account') !!}
<script>
    $(document).ready(function() {
        // set navigation link active
        $('.nav-link[href="#user-management"]').parent().addClass('active');
        $('.link-user-account').addClass('active')
        $('.link-user-account').parent().parent().parent().addClass('show')

    });
</script>
@endsection

resources/views/user_management/user_account_edit.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">User Account</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-description">Edit User Account</p>
                    <form class="forms-sample" id="form-edit-user-account" action="{{ route('user-account.update', $user->ID) }}" method="post">
                        @csrf
                        {{ method_field('PATCH') }}
                        @include('partials.form-input', [
                          'title'       => __('Email'),
                          'type'        => 'email',
                          'name'        => 'email',
                          'value'       => $user->email,
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Password'),
                          'type'        => 'password',
                          'name'        => 'password'
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Confirm Password'),
                          'type'        => 'password',
                          'name'        => 'password_confirmation'
                        ])
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a href="{{ route('user-account.index') }}" class="btn btn-dark">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\UserAccountRequest', '#form-edit-user-account') !!}
<script>
    $(document).ready(function() {
        // set navigation link active
        $('.nav-link[href="#user-management"]').parent().addClass('active');
        $('.link-user-account').addClass('active')
        $('.link-user-account').parent().parent().parent().addClass('show')

    });
</script>
@endsection

resources/views/user_management/user_account_index.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">User Account</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    @include('partials.alert')
                    <div>
                        <a class="btn btn-primary btn-icon-text" href="{{ route('user-account.create') }}">
                            <i class="mdi mdi-note-plus btn-icon-prepend"></i> 
                            Add User 
                        </a>
                    </div>
                    <br />
                    <div class="table-responsive">
                      <table class="table table-bordered" id="table">
                        <thead>
                          <tr>
                            <th> No </th>
                            <th> Username </th>
                            <th> Email </th>
                            <th> Created At </th>
                            <th> Updated At </th>
                            <th> Action </th>
                          </tr>
                        </thead>
                      </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(document).ready(function() {
        // datatable
        var table = $('#table').DataTable({
         processing: true,
         serverSide: true,
         searching: false,
         ordering: false,
         ajax: '{{ route('user-account.ajaxDatatable') }}',
         columns: [
             {
                "data": "id",
                render: function (data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                } 
             },
             {data: 'username', name: 'users.username'},
             {data: 'email', name: 'users.email'},
             {data: 'created_at', name: 'users.created_at'},
             {data: 'updated_at', name: 'users.updated_at'},
             { data: 'action', className: 'text-center', width: "20%" }
         ],
         "drawCallback": function(settings) {
         
          },            
             pageLength: 10,
         });
    });
</script>
@include('partials.datatable-delete', ['text' => 'User', 'table' => '#table'])
@endsection

resources/views/user_management/user_account_show.blade.php
@extends('layouts.app')
@section('content')
<div class="content-wrapper">
    <div class="page-header">
        <h3 class="page-title">User Account</h3>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <p class="card-description">Detail User Account</p>
                    <form class="forms-sample">
                        @include('partials.form-select', [
                          'title'    => __('Employee'),
                          'name'     => 'UserID',
                          'data'     => $employees,
                          'required' => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Email'),
                          'type'        => 'email',
                          'name'        => 'email',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Password'),
                          'type'        => 'password',
                          'name'        => 'password',
                          'required'    => true
                        ])
                        @include('partials.form-input', [
                          'title'       => __('Confirm Password'),
                          'type'        => 'password',
                          'name'        => 'password_confirmation',
                          'required'    => true
                        ])
                        <button type="submit" class="btn btn-primary mr-2">Submit</button>
                        <a href="{{ route('user-account.index') }}" class="btn btn-dark">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{!! JsValidator::formRequest('App\Http\Requests\UserAccountRequest', '#form-create-user-account') !!}
<script>
    $(document).ready(function() {
        // set navigation link active
        $('.nav-link[href="#user-management"]').parent().addClass('active');
        $('.link-user-account').addClass('active')
        $('.link-user-account').parent().parent().parent().addClass('show')

    });
</script>
@endsection