routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|c
*/

// for generate dummy record log
// Route::get('query', 'SeederController@dummyScan');

Route::get('/', function () {
    return redirect('dashboard');
});

Route::group(['middleware' => ['auth', 'web']], function () {
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

    // USER MANAGEMENT
    Route::prefix('user-management')->group(function () {
        // employee
        Route::get('/employee/ajaxDatatable', 'UserManagement\EmployeeController@ajaxDatatable')->name('employee.ajaxDatatable');
        Route::resource('employee', 'UserManagement\EmployeeController', ['names' => 'employee']);

        // user-account
        Route::get('/user-account/ajaxDatatable', 'UserManagement\UserAccountController@ajaxDatatable')->name('user-account.ajaxDatatable');
        Route::resource('user-account', 'UserManagement\UserAccountController', ['names' => 'user-account']);
    });

    // MASTER
    Route::prefix('master')->group(function () {
        // fever
        Route::resource('fever', 'Master\FeverController', ['names' => 'fever']);
        // absence
        Route::get('/absence/ajaxDatatable', 'Master\AbsenceController@ajaxDatatable')->name('absence.ajaxDatatable');
        Route::resource('absence', 'Master\AbsenceController', ['names' => 'absence']);
    });

    // MONITORING
    Route::prefix('monitoring')->group(function () {
        Route::get('/live-scan', 'Monitoring\LiveScanController@index')->name('live-scan');
        Route::get('/live-scan-monitor', 'Monitoring\LiveScanController@monitor')->name('live-scan-monitor');
    });

    // REPORT
    Route::prefix('report')->group(function () {
        // scanning report
        Route::get('/scanning-report/ajaxDatatable', 'Report\ScanningReportController@ajaxDatatable')->name('scanning-report.ajaxDatatable');
        Route::resource('scanning-report', 'Report\ScanningReportController', ['names' => 'scanning-report']);

        // absence report
        Route::get('/absence-report/ajaxDatatable', 'Report\AbsenceReportController@ajaxDatatable')->name('absence-report.ajaxDatatable');
        Route::resource('absence-report', 'Report\AbsenceReportController', ['names' => 'absence-report']);
    });
});

Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pinka - Pindai Muka</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- plugins:css -->
    <base href="{{ asset('') }}" />
    <link rel="stylesheet" href="./assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="./assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="./assets/vendors/select2/select2.min.css">
    <link rel="stylesheet" href="./assets/vendors/select2-bootstrap-theme/select2-bootstrap.min.css">
    <link rel="stylesheet" href="./assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="./assets/vendors/datatables/datatables.min.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <!-- End Plugin css for this page -->
    <!-- inject:css -->
    <!-- endinject -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="./assets/css/style.css">
    <!-- End layout styles -->
    <!-- Layout styles -->
    <link rel="stylesheet" href="./assets/css/custom.css">
    <!-- End layout styles -->
    <link rel="shortcut icon" href="./assets/images/favicon.png" />

    <script src="./assets/vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="./assets/vendors/chart.js/Chart.min.js"></script>
    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="./assets/js/off-canvas.js"></script>
    <script src="./assets/js/hoverable-collapse.js"></script>
    <script src="./assets/js/misc.js"></script>
    <script src="./assets/js/settings.js"></script>
    <script src="./assets/js/todolist.js"></script>
    <script src="./assets/vendors/select2/select2.min.js"></script>
    <script src="./assets/vendors/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script src="./assets/vendors/sweetalert/sweetalert.js"></script>
    <script src="./assets/vendors/datatables/datatables.min.js"></script>
    <!-- endinject -->
    <!-- End custom js for this page -->
    <!-- js validation -->
    <script src="./vendor/jsvalidation/js/jsvalidation.js"></script>
  </head>
  <body>
    <div class="container-scroller">
        @include('layouts.sidebar')

        <div class="container-fluid page-body-wrapper">
            @include('layouts.header')

            <div class="main-panel">
                @yield('content')

                @include('layouts.footer')
            </div>
        </div>
    </div>
  </body>
</html>

resources/views/layouts/footer.blade.php
<footer class="footer">
    <div class="d-sm-flex justify-content-center justify-content-sm-between">
        <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2020 PINKA. All rights reserved.</span>
    </div>
</footer>

resources/views/layouts/header.blade.php
<nav class="navbar p-0 fixed-top d-flex flex-row">
    <div class="navbar-brand-wrapper d-flex d-lg-none align-items-center justify-content-center">
        <a class="navbar-brand brand-logo-mini" href="./index.html"><img src="./assets/images/logo-mini.svg" alt="logo" /></a>
    </div>
    <div class="navbar-menu-wrapper flex-grow d-flex align-items-stretch">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
            <span class="mdi mdi-menu"></span>
        </button>
        <ul class="navbar-nav navbar-nav-right">
            <li class="nav-item dropdown">
                <a class="nav-link" id="profileDropdown" href="#" data-toggle="dropdown">
                    <div class="navbar-profile">
                        @php
                            $img = Auth::user()->employee->UserID;
                            $path = Config('facemanager.folder') . '/facedata/' . $img . '.jpg';
                        @endphp
                        <img class="img-xs rounded-circle" src="{{ asset($path) }}" alt="" />
                        <p class="mb-0 d-none d-sm-block navbar-profile-name">{{ Auth::user()->employee->UserName }}</p>
                        <i class="mdi mdi-menu-down d-none d-sm-block"></i>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="profileDropdown">
                    <a class="dropdown-item preview-item" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
                        <div class="preview-thumbnail">
                            <div class="preview-icon bg-dark rounded-circle">
                                <i class="mdi mdi-logout text-danger"></i>
                            </div>
                        </div>
                        <div class="preview-item-content">
                            <p class="preview-subject mb-1">
                              Logout
                              <form id="logout-form" action="{{ route('logout') }}" method="POST" class="hidden">
                                  {{ csrf_field() }}
                              </form>
                            </p>
                        </div>
                    </a>
                </div>
            </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
            <span class="mdi mdi-format-line-spacing"></span>
        </button>
    </div>
</nav>

resources/views/layouts/sidebar.blade.php
<!-- partial:./partials/_sidebar.html -->
<nav class="sidebar sidebar-offcanvas" id="sidebar">
    <div class="sidebar-brand-wrapper d-none d-lg-flex align-items-center justify-content-center fixed-top">
        <a class="sidebar-brand brand-logo logo-style" href="{{ url('') }}">
            <img src="{{ asset('assets/images/pinka.png') }}" />
        </a>
        <a class="sidebar-brand brand-logo-mini logo-style" href="{{ url('') }}">
            <img src="{{ asset('assets/images/p.png') }}" />
        </a>
    </div>
    <ul class="nav">
        <li class="nav-item profile">
            <div class="profile-desc">
                <div class="profile-pic">
                    <div class="count-indicator">
                        @php
                            $img = Auth::user()->employee->UserID;
                            $path = Config('facemanager.folder') . '/facedata/' . $img . '.jpg';
                        @endphp
                        <img class="img-xs rounded-circle" src="{{ asset($path) }}" alt="" />
                    </div>
                    <div class="profile-name">
                        <h5 class="mb-0 font-weight-normal">{{ \Auth::user()->employee->UserName }}</h5>
                        <span> {{ \Auth::user()->employee->department->GroupName }} </span>
                    </div>
                </div>
            </div>
        </li>
        <li class="nav-item nav-category">
            <span class="nav-link">Navigation</span>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" href="{{ route('dashboard') }}">
                <span class="menu-icon">
                    <i class="mdi mdi-speedometer"></i>
                </span>
                <span class="menu-title">Dashboard</span>
            </a>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#user-management" aria-expanded="false" aria-controls="user-management">
                <span class="menu-icon">
                    <i class="mdi mdi-account-key"></i>
                </span>
                <span class="menu-title">User Management</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="user-management">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('employee.index') }}">
                            Employee
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link-user-account" href="{{ route('user-account.index') }}">
                            User Account
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#master" aria-expanded="false" aria-controls="master">
                <span class="menu-icon">
                    <i class="mdi mdi-wrench"></i>
                </span>
                <span class="menu-title">Master</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="master">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{ route('fever.index') }}">Fever</a></li>
                    <li class="nav-item"><a class="nav-link link-absence" href="{{ route('absence.index') }}">Absence</a></li>
                </ul>
            </div>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#monitoring" aria-expanded="false" aria-controls="monitoring">
                <span class="menu-icon">
                    <i class="mdi mdi-monitor"></i>
                </span>
                <span class="menu-title">Monitoring</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="monitoring">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('live-scan') }}">
                            Live Scan
                        </a>
                    </li>
                </ul>
            </div>
        </li>
        <li class="nav-item menu-items">
            <a class="nav-link" data-toggle="collapse" href="#history" aria-expanded="false" aria-controls="history">
                <span class="menu-icon">
                    <i class="mdi mdi-history"></i>
                </span>
                <span class="menu-title">Report</span>
                <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="history">
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{ route('scanning-report.index') }}">Scanning Report</a></li>
                </ul>
                <ul class="nav flex-column sub-menu">
                    <li class="nav-item"><a class="nav-link" href="{{ route('absence-report.index') }}">Absence Report</a></li>
                </ul>
            </div>
        </li>
    </ul>
</nav>